### PR TITLE
Render an error message to the log when the api_url can't be connected to (closes #747)

### LINKED ISSUE #747: render a useful error message on edit_contacts when js can't connect to the api
render a useful error message on edit_contacts if the JavaScript is unable to connect to the api

Refer #746

### PR DESCRIPTION
**Pull request by Hobbsee**
As we move more web functionality to call the web API, it seems like we want the web gateway to always fail if it can't connect.

This now shows:

```
2015-01-28T11:27:41.031525+11:00 [ERROR] :: flapjack-web :: api_url not specified, or is not a valid http or https URI (httz://localhost:3087/)

2015-01-28T11:26:12.244711+11:00 [ERROR] :: flapjack-web :: Could not connect to api_url: (http://localhost:3087/): Connection refused - connect(2) for "localhost" port 3087
```

This now also fails to start up the web UI.

### CODE REVIEW

**Comment by jessereynolds** [comment]
It's possible the api will be inaccessible from the web gateway, eg if they're behind load balancers that the gateways themselves can't connect to. So I think this is dangerous from this perspective. 

Also, with the web gateway as it stands currently, it's kind of convenient to be able to disable editing, and the only way to do that is to point the api url at something that gives a connection refused or otherwise is incorrect. Not ideal but yes.

**Comment by Hobbsee** [comment]
> It's possible the api will be inaccessible from the web gateway, eg if they're behind load balancers that the gateways themselves can't connect to. So I think this is dangerous from this perspective. 

I'm missing something here - does flapjack fully function in this case?  Aren't we moving towards calling more api functions, rather than talking to the redis directly?

> Also, with the web gateway as it stands currently, it's kind of convenient to be able to disable editing, and the only way to do that is to point the api url at something that gives a connection refused or otherwise is incorrect. Not ideal but yes.

So, a read only flag sounds useful (particularly if we eventually support auth, read-only on a per-user basis), and should be added separately.  What should be locked off here?   
 - Contacts
 - Scheduling maintenance?
 - Acknowledging alerts?

**Comment by ali-graham** [comment]
> What should be locked off here? 

In API terms, anything but a GET, basically. You shouldn'be able to do anything that changes data.

**Comment by jessereynolds** [comment]
>> It's possible the api will be inaccessible from the web gateway, eg if they're behind load balancers that the gateways themselves can't connect to. So I think this is dangerous from this perspective. 

>I'm missing something here - does flapjack fully function in this case?  Aren't we moving towards calling more api functions, rather than talking to the redis directly?

Yep flapjack would fully function in this case. The API is accessible to external consumers on the configured api_url, but not by the web gateway server code. API could still be accessible by the javascript running client side that's served out by the web gateway, though.

**Comment by Hobbsee** [comment]
Fair enough.

I've dropped this back to a warning:

```
2015-01-29T16:46:03.049944+11:00 [WARN] :: flapjack-web :: Could not connect to api_url: (http://localhost:3085/): Connection refused - connect(2) for "localhost" port 3085 - some functionality will be unavailable
```

I've also added a label in place of the edit contacts button (similar to the beta when the api_url is available).  Do you have thoughts on the text / look / whether it needs to pop up in pure javascript instead?

screen shot 2015-01-29 at 4 49 28 pm

**Comment by jessereynolds** [comment]
That's a good error message to show in the UI, style is fine I reckon. 

But it needs to be generated by the javascript client-site if it can't connect, rather than by the web gateway server-side. This is because of aforementioned reasons, where the web gateway server-side may not have access to the API at the same URL that the client is accessing the API at. Basically from the web gateway server-side is the wrong place to determine if the API is accessible to the client's browser. 

Eg:
- api_url is set to http://flapjack-api.example.com/ which is a reverse proxy in front of the flapjack server(s)
- the backend flapjack server(s) running the web gateway are unable to connect to this reverse proxy server

**Comment by Hobbsee** [comment]
Fair enough.  I've gotten nowhere with javascript, and removed the server-side check, and left in the warning if the server can't talk to the web api during startup. 

If that's considered useful, then feel free to merge it, else just close this PR.

**Comment by jessereynolds** [comment]
I don't think it's useful to log when the web gateway server-side can't establish a connection to the api as it has little bearing on whether the browser client-side will be able to establish a connection to the api.

**Pull request closed without merging**
