### PR TITLE
Remove /edit_contacts interface from web UI (closes #798)

### LINKED ISSUE #798: Remove the /edit_contacts interface
remove the /edit_contacts interface for the 2.0 release. 

we can bring in a replacement in a 2.x release without breaking backwards compatibility. 

for now, data changes are via the API

### PR DESCRIPTION
**Pull request by Hobbsee**

### CODE REVIEW

**Comment by Hobbsee** [comment]
Replaced the edit contacts button with the following:

screen shot 2015-03-03 at 3 25 46 pm

I think I've gotten all the parts here, but if someone could double check, that'd be great!

**Comment by ali-graham** [comment]
I think `gateways/web/public/js` -> `backbone.js`, `backbone.jsonapi.js`, `select2.js` and `underscore.js` can also go.

**Comment by Hobbsee** [comment]
Excellent point - web UI seems to work without those, and I'm not seeing any JS errors.

**Comment by ali-graham** [comment]
There are also a couple of select2 css files in `gateways/web/public/css`.

**Comment by ali-graham** [comment]
And indeed some select2 png/gif files in `gateways/web/public/img`.

**Comment by Hobbsee** [comment]
Thanks!  More select2 files bite the dust!

**Pull request merged**
