### PR TITLE
(1.x) remove PagerDuty basic auth

### PR DESCRIPTION
**Pull request by ali-graham**
The word from @SarahKowalik is that PagerDuty will be removing HTTP basic auth on November 4. Flapjack already supported (and preferred) token-based auth, this PR just removes the backwards-compatible support for the old behaviour, and the associated data.

### CODE REVIEW

**Comment by jessereynolds** [comment]
If people have written an integration with Flapjack to update contacts, and have included old and new pagerduty credentails, their integrations will fail if they apply a 1.x update (failure from the flapjack api about unexpected fields I guess?). Hmmm.

**Comment by ali-graham** [comment]
Silently dropped I think.

**Comment by jessereynolds** [comment]
That sounds good then!

**Comment by ali-graham** [comment]
Thanks for the review @jessereynolds !

**Pull request merged**
