### PR TITLE
Gammu SMS gateway

### PR DESCRIPTION
**Pull request by paologlim**
Add a gateway for sending alerts via SMS using Gammu. Basically we insert the alert details in a mysql database, and Gammu picks it up and sends it.

### CODE REVIEW

**Comment by ali-graham** [comment]
Looks good, will need a couple more changes:

* either `mysql2` will need to be added to the gemspec, or we'll need some sort of fallback if the `mysql2` gem is not found.
* the example config file should have a section for this gateway

The travis build failure is to do with some hackery around a different Gemfile for Ruby 1.9 -- ignore that for the moment, I can ensure it's working befoe merge. 

Once merged, I can forward-port the functionality to the `master` branch.

**Comment by ali-graham** [comment]
Also, it looks like Gammu supports multiple databases; it might be good to allow this gateway to accept a number of different database types, and check for the presence of the relevant ruby gem before initialising the configured DB connection.

Before getting to this, I''ll be working on changes in the `maint/1.x` branch (to support Ruby 2.2) which will stop this PR from merging cleanly, but I can fix as appropriate when the time comes

**Comment by paologlim** [comment]
@ali-graham Travis build is now ok. Do you think you can merge this now?

**Comment by ali-graham** [comment]
It'll need some changes to work with some stuff I changed today -- I'll fix that and merge tomorrow morning, as the `maint/1.x` branch should always be in a releasable state.

Thanks for the contribution! We'll look at expanding the gateway to handle config for other databases once it's been merged.

**Comment by ali-graham** [comment]
Actually, cancel that, my other changes weren't merged yet. :smile:

**Comment by jessereynolds** [comment]
I've spent much of this week encouraging omnibus-flapjack to build packages including libmysqlclient and fixing broken package install tests subsequent to this merge, so I don't have any more time to spend fixing things that [this PR breaks](https://github.com/flapjack/omnibus-flapjack/issues/73). Here's the last problem I found, which was the straw that broke the camel's back:
- default alert templates must be included with the gateway, and example template override paths commented out in the config

Gateways that require connector libraries such as libmysqlclient will be easier to implement in Flapjack 2.x when we've implemented a well defined plugin API for gateways, and all gateways then become plugins. 

Sorry to unmerge.

**Pull request merged**
