### PR TITLE
1.x pagerduty ack retrieval improvements

### PR DESCRIPTION
**Pull request by jessereynolds**
This increases the expiry on pagerduty acks running semaphore to 1 hour. 

Should address #854 in a fairly terrible kind of way.

### CODE REVIEW

**Comment by Hobbsee** [comment]
Looks good to me.

**Comment by ali-graham** [comment]
[This](https://github.com/flapjack/flapjack/blob/dec15a27a556e886b455f0f0d3ed4195d8f36f6c/lib/flapjack/gateways/pagerduty.rb#L210-L217) loads all unacked failing checks for each originally unacked failing check, it's probably the main offender in time usage. It would make sense to see there whether the check that's the subject of the loop is still failing and unacknowledged instead.

Increasing the timeout is a good idea as well, but let's do what we can to fix the underlying problem.

**Comment by jessereynolds** [comment]
Oh yeah, that's awful. Fixing...

**Comment by jessereynolds** [comment]
panda what have i done

**Comment by ali-graham** [comment]
:+1:

**Pull request merged**
