### PR TITLE
Puma rather than Webrick, plus exception requests are now logged in the access_log

### LINKED ISSUE #794: Better exception handling in Web and API Webricks
Currently in master 794ca24 accessing /self_stats in the web UI returns an internal server error. Nothing about this request is logged in flapjack.log or web_access.log. What should happen when an exception occurs processing a request:
- the request, including response status code, is logged in web_access.log
- the stack trace is logged in flapjack.log along with other details about the request 
- a prettier error page, or json api response, is returned to the http client

### PR DESCRIPTION
**Pull request by ali-graham**
Fixes #794.

(A brief aside to curse Rack and Sinatra, which made this harder than it needed to be, and the code hackier.)

### CODE REVIEW

**Comment by Hobbsee** [comment]
Looks good to me.  Shouldn't the exceptions go to an error_log though?

**Comment by ali-graham** [comment]
I followed the brief in #794 :)

It can be useful to have them inline with other logged data, we could probably design them better so that they can be filtered properly by log parsing tools though.

**Comment by jessereynolds** [comment]
Error details go into flapjack.log, 5xx status code request summaries still got into the access_log. That's right @ali-graham ?

**Comment by ali-graham** [comment]
Yes. Requests finishing with 500s weren't being access_logged properly before that second commit.

**Comment by jessereynolds** [comment]
:tada: :balloon:

**Pull request merged**
